Controllers/OrderController.cs
using System.Threading.Tasks;
using dotnet_store.Models;
using dotnet_store.Services;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace dotnet_store.Controllers;

[Authorize]
public class OrderController : Controller
{
    private ICartService _cartService;
    private readonly IConfiguration _configuration;
    private readonly DataContext _context;
    public OrderController(ICartService cartService, DataContext context, IConfiguration configuration)
    {
        _cartService = cartService;
        _context = context;
        _configuration = configuration;
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Index()
    {
        return View(_context.Orders.ToList());
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Details(int id)
    {
        var order = _context.Orders
                    .Include(i => i.OrderItems)
                    .ThenInclude(i => i.Urun)
                    .FirstOrDefault(i => i.Id == id);

        return View(order);
    }

    public async Task<ActionResult> Checkout()
    {
        ViewBag.Cart = await _cartService.GetCart(User.Identity?.Name!);
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Checkout(OrderCreateModel model)
    {
        var username = User.Identity?.Name!;
        var cart = await _cartService.GetCart(username);

        if (cart.CartItems.Count == 0)
        {
            ModelState.AddModelError("", "Sepetinizde ürün yok");
        }

        if (ModelState.IsValid)
        {
            var order = new Order
            {
                AdSoyad = model.AdSoyad,
                Telefon = model.Telefon,
                AdresSatiri = model.AdresSatiri,
                PostaKodu = model.PostaKodu,
                Sehir = model.Sehir,
                SiparisNotu = model.SiparisNotu!,
                SiparisTarihi = DateTime.Now,
                ToplamFiyat = cart.Toplam(),
                Username = username,
                OrderItems = cart.CartItems.Select(ci => new Models.OrderItem
                {
                    UrunId = ci.UrunId,
                    Fiyat = ci.Urun.Fiyat,
                    Miktar = ci.Miktar
                }).ToList()
            };

            var payment = await ProcessPayment(model, cart);

            if (payment.Status == "success")
            {
                _context.Orders.Add(order);
                _context.Carts.Remove(cart);

                await _context.SaveChangesAsync();

                return RedirectToAction("Completed", new { orderId = order.Id });
            }
            else
            {
                ModelState.AddModelError("", payment.ErrorMessage);
            }
        }

        ViewBag.Cart = cart;
        return View(model);
    }

    public ActionResult Completed(string orderId)
    {
        return View("Completed", orderId);
    }

    public async Task<ActionResult> OrderList()
    {
        var username = User.Identity?.Name;
        var orders = await _context.Orders
                .Include(i => i.OrderItems)
                .ThenInclude(i => i.Urun)
                .Where(i => i.Username == username)
                .ToListAsync();

        return View(orders);
    }

    private async Task<Payment> ProcessPayment(OrderCreateModel model, Cart cart)
    {
        Options options = new Options();
        options.ApiKey = _configuration["PaymentAPI:APIKey"];
        options.SecretKey = _configuration["PaymentAPI:SecretKey"];
        options.BaseUrl = "https://sandbox-api.iyzipay.com";

        CreatePaymentRequest request = new CreatePaymentRequest();
        request.Locale = Locale.TR.ToString();
        request.ConversationId = Guid.NewGuid().ToString();
        request.Price = cart.AraToplam().ToString();
        request.PaidPrice = cart.AraToplam().ToString();
        request.Currency = Currency.TRY.ToString();
        request.Installment = 1;
        request.BasketId = "B67832";
        request.PaymentChannel = PaymentChannel.WEB.ToString();
        request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

        PaymentCard paymentCard = new PaymentCard();
        paymentCard.CardHolderName = model.CartName;
        paymentCard.CardNumber = model.CartNumber;
        paymentCard.ExpireMonth = model.CartExpirationMonth;
        paymentCard.ExpireYear = model.CartExpirationYear;
        paymentCard.Cvc = model.CartCVV;
        paymentCard.RegisterCard = 0;
        request.PaymentCard = paymentCard;

        Buyer buyer = new Buyer();
        buyer.Id = "BY789";
        buyer.Name = model.AdSoyad;
        buyer.Surname = "Doe";
        buyer.GsmNumber = model.Telefon;
        buyer.Email = "email@email.com";
        buyer.IdentityNumber = "74300864791";
        buyer.LastLoginDate = "2015-10-05 12:43:35";
        buyer.RegistrationDate = "2013-04-21 15:12:09";
        buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
        buyer.Ip = "85.34.78.112";
        buyer.City = model.Sehir;
        buyer.Country = "Turkey";
        buyer.ZipCode = model.PostaKodu;
        request.Buyer = buyer;

        Address address = new Address();
        address.ContactName = model.AdSoyad;
        address.City = model.Sehir;
        address.Country = "Turkey";
        address.Description = model.AdresSatiri;
        address.ZipCode = model.PostaKodu;
        request.ShippingAddress = address;
        request.BillingAddress = address;

        List<BasketItem> basketItems = new List<BasketItem>();

        foreach (var item in cart.CartItems)
        {
            BasketItem basketItem = new BasketItem();
            basketItem.Id = item.CartItemId.ToString();
            basketItem.Name = item.Urun.UrunAdi;
            basketItem.Category1 = "Telefon";
            basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
            basketItem.Price = item.Urun.Fiyat.ToString();

            basketItems.Add(basketItem);
        }


        request.BasketItems = basketItems;

        return await Payment.Create(request, options);
    }
}

Controllers/UrunController.cs
using System.Threading.Tasks;
using dotnet_store.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace dotnet_store.Controllers;

[Authorize(Roles = "Admin")]
public class UrunController : Controller
{
    private readonly DataContext _context;
    public UrunController(DataContext context)
    {
        _context = context;
    }

    public ActionResult Index(int? kategori)
    {
        var query = _context.Urunler.AsQueryable();

        if (kategori != null)
        {
            query = query.Where(i => i.KategoriId == kategori);
        }

        var urunler = query.Select(i => new UrunGetModel
        {
            Id = i.Id,
            UrunAdi = i.UrunAdi,
            Fiyat = i.Fiyat,
            Aktif = i.Aktif,
            Anasayfa = i.Anasayfa,
            KategoriAdi = i.Kategori.KategoriAdi,
            Resim = i.Resim
        }).ToList();

        ViewBag.Kategoriler = new SelectList(_context.Kategoriler.ToList(), "Id", "KategoriAdi", kategori);

        return View(urunler);
    }

    [AllowAnonymous]
    public ActionResult List(string url, string q)
    {
        var query = _context.Urunler.Where(i => i.Aktif);

        if (!string.IsNullOrEmpty(url))
        {
            query = query.Where(i => i.Kategori.Url == url);
        }

        if (!string.IsNullOrEmpty(q))
        {
            query = query.Where(i => i.UrunAdi.ToLower().Contains(q.ToLower()));

            ViewData["q"] = q;
        }

        return View(query.ToList());
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
        var urun = _context.Urunler.Find(id);

        if (urun == null)
        {
            return RedirectToAction("Index", "Home");
        }

        ViewData["BenzerUrunler"] = _context.Urunler
                                        .Where(i => i.Aktif && i.KategoriId == urun.KategoriId && i.Id != id)
                                        .Take(4)
                                        .ToList();

        return View(urun);
    }

    public ActionResult Create()
    {
        ViewBag.Kategoriler = new SelectList(_context.Kategoriler.ToList(), "Id", "KategoriAdi");
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(UrunCreateModel model)
    {
        if (model.Resim == null || model.Resim.Length == 0)
        {
            ModelState.AddModelError("Resim", "Resim seçmelisiniz");
        }

        if (ModelState.IsValid)
        {
            var fileName = Path.GetRandomFileName() + ".jpg";
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await model.Resim!.CopyToAsync(stream);
            }

            var entity = new Urun()
            {
                UrunAdi = model.UrunAdi,
                Aciklama = model.Aciklama,
                Fiyat = model.Fiyat ?? 0,
                Aktif = model.Aktif,
                Anasayfa = model.Anasayfa,
                KategoriId = (int)model.KategoriId!,
                Resim = fileName
            };

            _context.Urunler.Add(entity);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        ViewBag.Kategoriler = new SelectList(_context.Kategoriler.ToList(), "Id", "KategoriAdi");
        return View(model);
    }

    public ActionResult Edit(int id)
    {
        var entity = _context.Urunler.Select(i => new UrunEditModel
        {
            Id = i.Id,
            UrunAdi = i.UrunAdi,
            Aciklama = i.Aciklama,
            Aktif = i.Aktif,
            Anasayfa = i.Anasayfa,
            Fiyat = i.Fiyat,
            KategoriId = i.KategoriId,
            ResimAdi = i.Resim
        }).FirstOrDefault(i => i.Id == id);

        ViewBag.Kategoriler = new SelectList(_context.Kategoriler.ToList(), "Id", "KategoriAdi");
        return View(entity);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(int id, UrunEditModel model)
    {
        if (id != model.Id)
        {
            return RedirectToAction("Index");
        }

        if (ModelState.IsValid)
        {
            var entity = _context.Urunler.FirstOrDefault(i => i.Id == model.Id);

            if (entity != null)
            {
                if (model.Resim != null)
                {
                    var fileName = Path.GetRandomFileName() + ".jpg";
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await model.Resim!.CopyToAsync(stream);
                    }

                    entity.Resim = fileName;
                }

                entity.UrunAdi = model.UrunAdi;
                entity.Aciklama = model.Aciklama;
                entity.Fiyat = model.Fiyat ?? 0;
                entity.Aktif = model.Aktif;
                entity.Anasayfa = model.Anasayfa;
                entity.KategoriId = (int)model.KategoriId!;

                _context.SaveChanges();

                TempData["Mesaj"] = $"{entity.UrunAdi} ürünü güncellendi.";

                return RedirectToAction("Index");
            }

        }

        ViewBag.Kategoriler = new SelectList(_context.Kategoriler.ToList(), "Id", "KategoriAdi");
        return View(model);
    }

    public ActionResult Delete(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("Index");
        }

        var entity = _context.Urunler.FirstOrDefault(i => i.Id == id);

        if (entity != null)
        {
            return View(entity);
        }
        return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteConfirm(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("Index");
        }

        var entity = _context.Urunler.FirstOrDefault(i => i.Id == id);

        if (entity != null)
        {
            _context.Urunler.Remove(entity);
            _context.SaveChanges();

            TempData["Mesaj"] = $"{entity.UrunAdi} isimli ürün silindi.";
        }
        return RedirectToAction("Index");
    }


}

Views/Shared/Partials/Site/_AccountSideBar.cshtml
<div class="list-group mb-3">
    <a asp-controller="Account" asp-action="EditUser" class="list-group-item list-group-item-action">
        Kullanıcı Bilgileri
    </a>
    <a asp-controller="Account" asp-action="UserEdit" class="list-group-item list-group-item-action">
        Adres Bilgileri
    </a>
    <a asp-controller="Order" asp-action="OrderList" class="list-group-item list-group-item-action">
        Siparişler
    </a>
    <a asp-controller="Account" asp-action="ChangePassword" class="list-group-item list-group-item-action">
        Parola Değiştir
    </a>
</div>

Views/Shared/Partials/Site/_Footer.cshtml
<footer class="mt-3 py-4 bg-primary">
    <div class="container">
        <div class="row gy-3">
            <div class="col-md-6 col-lg-4">
                <form>
                    <div class="input-group">
                        <input type="email" class="form-control" placeholder="Email giriniz.">
                        <button type="button" class="btn btn-outline-warning">Abone Ol</button>
                    </div>
                </form>
            </div>
            <div class="col-md-6 col-lg-8">
                <nav class="text-center text-md-end">
                    <a href="#" class="btn btn-icon btn-outline-warning">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="#" class="btn btn-icon btn-outline-warning">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="#" class="btn btn-icon btn-outline-warning">
                        <i class="fab fa-youtube"></i>
                    </a>
                    <a href="#" class="btn btn-icon btn-outline-warning">
                        <i class="fab fa-twitter"></i>
                    </a>
                </nav>
            </div>
            <div class="col-12">
                <p class="text-center text-md-start text-white">
                    2026 Tüm hakları saklıdır.
                </p>
            </div>
        </div>
    </div>
</footer>

Views/Shared/Partials/Site/_Menu.cshtml
@model List<Kategori>

<nav class="nav nav-pills flex-column flex-nowrap overflow-auto slider_nav">
    @foreach (var kategori in Model)
    {
        <a href="/urunler/@kategori.Url" class="nav-link">@kategori.KategoriAdi</a>
    }

</nav>

Views/Shared/Partials/Site/_Message.cshtml
@if (TempData["Mesaj"] != null)
{
    <div class="alert alert-warning mb-0 text-center">
        @TempData["Mesaj"]
    </div>
}

Views/Shared/Partials/Site/_Topbar.cshtml
<section class="top-bar">
    <div class="container">
        <div class="row gy-2 align-items-center">
            <div class="col-lg-2 col-sm-4 col-4">
                <a href="/" class="navbar-brand"><i class="fa-solid fa-truck-fast"></i> E-Commerce</a>
            </div>

            <div class="col-lg-5 col-sm-8 col-8 order-lg-last">
                <div class="text-end">

                    @if (User.Identity?.IsAuthenticated == true)
                    {
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-controller="Admin" asp-action="Index" class="btn btn-danger" target="_blank">
                                <i class="fa-solid fa-lock"></i> <span class="ms-1 d-none d-sm-inline-block">Admin</span>
                            </a>
                        }

                        <a asp-controller="Account" asp-action="EditUser" class="btn btn-light">
                            <i class="fa fa-user"></i> <span class="ms-1 d-none d-sm-inline-block">Hesabım</span>
                        </a>
                        <a asp-controller="Account" asp-action="LogOut" class="btn btn-light">
                            <i class="fa fa-heart"></i> <span class="ms-1 d-none d-sm-inline-block">Çıkış</span>
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Login" class="btn btn-light">
                            <i class="fa-solid fa-right-to-bracket"></i> <span
                                class="ms-1 d-none d-sm-inline-block">Giriş</span>
                        </a>
                        <a asp-controller="Account" asp-action="Create" class="btn btn-light">
                            <i class="fa-solid fa-user-plus"></i> <span class="ms-1 d-none d-sm-inline-block">Üye Ol</span>
                        </a>
                    }

                    <a asp-controller="Cart" asp-action="Index" class="btn btn-light">
                        <i class="fa fa-shopping-cart"></i> <span class="ms-1 d-none d-sm-inline-block">Sepetim</span>
                    </a>

                </div>
            </div>
            <div class="col-lg-5">
                <form asp-controller="Urun" asp-action="List" method="get">
                    <div class="input-group">
                        <input name="q" type="text" placeholder="Anahtar kelime" class="form-control"
                            value="@ViewData["q"]">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

Views/Shared/Partials/Site/_UrunCard.cshtml
@model Urun

<div class="card shadow">
    <div class="img-wrap">
        <span class="badge bg-success">İndirim</span>
        <img src="~/img/@Model.Resim" alt="@Model.UrunAdi" class="card-img-top">
    </div>

    <div class="border-top info-wrap">
        <a href="#" class="float-end btn btn-light">
            <i class="fa-regular fa-heart"></i>
        </a>
        <a asp-controller="Urun" asp-action="Details" asp-route-id="@Model.Id"
            class="title text-truncate">@Model.UrunAdi</a>
        <div class="price-wrap">
            <span class="price-discount">@Model.Fiyat ₺</span>
            @* <del class="price">49.999 ₺</del> *@
        </div>
    </div>
</div>